name: laravel_action_test_name
on:
  push:
    branches:
      - master

jobs:
  laravel_action_test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup PHP without any shared extensions except mbstring
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"
      - name: generate a file to test
        run: echo "Laravel action test file" > laravel_action_test_file.txt
      - name: show message
        run: echo "Laravel action test successful"
      - name: php version
        run: php -v
      - name: composer version
        run: composer -V
      - name: list files
        run: ls -la
